name: CI

on:
  push:
    branches:
      - main

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-slim
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Check workflows
      run: go run github.com/rhysd/actionlint/cmd/actionlint@v1.7.12

  release:
    name: Release?
    needs: [verify]
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-slim
    steps:
    - name: Release?
      id: release
      uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
      with:
        config-file: .github/release-please-config.json
        manifest-file: .github/release-please-manifest.json
